const actionType = {
  GET_ALL_JOBS_REQUEST: "GET_ALL_JOBS_REQUEST",
  GET_ALL_JOBS_SUCCESS: "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAILURE: "GET_ALL_JOBS_FAILURE",
  ADD_NEW_JOB_REQUEST: "ADD_NEW_JOB_REQUEST",
  ADD_NEW_JOB_SUCCESS: "ADD_NEW_JOB_SUCCESS",
  ADD_NEW_JOB_FAILURE: "ADD_NEW_JOB_FAILURE",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  DELETE_JOB_REQUEST: "DELETE_JOB_REQUEST",
  DELETE_JOB_SUCCESS: "DELETE_JOB_SUCCESS",
  DELETE_JOB_FAILURE: "DELETE_JOB_FAILURE",
  UPDATE_JOB_REQUEST: "UPDATE_JOB_REQUEST",
  UPDATE_JOB_SUCCESS: "UPDATE_JOB_SUCCESS",
  UPDATE_JOB_FAILURE: "UPDATE_JOB_FAILURE",
  SET_SINGLE_JOB: "SET_SINGLE_JOB",
  GET_SELECTED_JOB: "GET_SELECTED_JOB",
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export { actionType }