const actionType = {
  GET_ALL_JOBS_REQUEST: "GET_ALL_JOBS_REQUEST",
  GET_ALL_JOBS_SUCCESS: "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAILURE: "GET_ALL_JOBS_FAILURE",
  ADD_NEW_JOB_REQUEST: "ADD_NEW_JOB_REQUEST",
  ADD_NEW_JOB_SUCCESS: "ADD_NEW_JOB_SUCCESS",
  ADD_NEW_JOB_FAILURE: "ADD_NEW_JOB_FAILURE"
}

export { actionType }